### ISSUE TITLE
exit non-zero if plek deployment fails

### ISSUE THREAD

**Issue by thadeetrompetter** [voorhoede/plek#69]
To know if the deployment with plek ended in failure, i'd expect a non-zero exit code.
Instead, the deployment exits OK printing a json string that contains some info about what went wrong.

Example:

```
{ stdout: '',
  stderr: '\u001b[2K\u001b[G> Assigning alias [redacted].now.sh to deployment [redacted].now.sh\n\u001b[2K\u001b[G> Error! The alias [redacted].now.sh is a deployment URL or it\'s in use by a different team.\n' }
```

**Comment by Siilwyn** [comment]
![image](https://user-images.githubusercontent.com/5701149/50689376-cb2df100-1029-11e9-908e-82308f4a9e6e.png)

:tada:
